@startuml "Diagrama Relacional"

Entity Mesa{
    id_Integer <<PK>>
    --
    numero: varchar <<NN>>
}

Entity Pedido{
    id: Integer <<PK>>
    cliente: varchar
    estado: varchar <<NN>>
    --
    id_mesa: Integer <<FK>> <<NN>>
    --
    id_tipo_opcion: Integer <<FK>> <<NN>>
    --
    id_sopa: Integer <<FK>>
    id_principio: Integer <<FK>> <<NN>>
    id_carne: Integer <<FK>> <<NN>>
    id_ensalada: Integer <<FK>>
    id_jugo: Integer <<FK>> <<NN>>
}

Entity Adicional{
    nombre: varchar <<NN>>
    precio: Integer <<NN>>
    --
    id: Integer <<PK>>
}

Entity Sopa{
    id: Integer <<PK>>
    --
    nombre: varchar <<NN>>
}

Entity Principio{
    id: Integer <<PK>>
    --
    nombre: varchar <<NN>>
}

Entity Carne {
    id: Integer <<PK>>
    --
    nombre: varchar <<NN>>
}

Entity Ensalada {
    id: Integer <<PK>>
    --
    nombre: varchar <<NN>>
}

Entity Jugo {
    id: Integer <<PK>>
    --
    nombre: varchar <<NN>>
}

Entity PedidoAdicional {
    --
    id_adicional: Integer <<PK>> <<FK>>
    id: Integer <<PK>> <<FK>>
}

Entity TipoOpcion {
    id: Integer <<PK>>
    --
    tipo: varchar {Bandeja | Completo}
    precio: Integer <<NN>>
}

Mesa |o--|{ Pedido

Pedido -right-|{ PedidoAdicional
Adicional --|{ PedidoAdicional

Pedido }|-left-|| TipoOpcion

Pedido }o-- Sopa
Pedido }|-- Principio
Pedido }|-- Carne
Pedido }o-- Ensalada
Pedido }|-- Jugo

@enduml